# Generated by Django 4.1.7 on 2023-11-10 07:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tables.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersAddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/avatars/')),
                ('degree', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_patent', models.CharField(max_length=60)),
                ('year_of_receipt', models.IntegerField()),
                ('number_of_the_patent', models.IntegerField()),
                ('copy_of_the_security_document', models.FileField(upload_to=tables.models.user_upload_path)),
                ('the_object_for_which_the_security_document_was_received', models.CharField(max_length=40)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi9', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_of_the_AlmaU_School_or_management_on_the_scientific_management_of_the_laboratory_or_center', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi8', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_of_the_authorized_body_on_awarding_an_academic_degree_in_the_field_of_art_or_sports', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi7', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doctoral_student', models.CharField(max_length=60)),
                ('surname_of_the_doctoral_student', models.CharField(max_length=60)),
                ('school', models.CharField(max_length=100)),
                ('topic_of_the_dissertation', models.CharField(max_length=100)),
                ('year_of_award', models.IntegerField()),
                ('decision_of_the_authorized_body_on_awarding_an_academic_degree', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doctoral_student', models.CharField(max_length=60)),
                ('surname_of_the_doctoral_student', models.CharField(max_length=60)),
                ('university_of_doctoral_studies', models.CharField(max_length=100)),
                ('faculty_of_doctoral_student', models.CharField(max_length=100)),
                ('year_of_the_beginning_of_studies', models.IntegerField()),
                ('year_of_graduation', models.IntegerField()),
                ('topic_of_the_dissertation', models.CharField(max_length=40)),
                ('decision_of_the_academic_council_on_scientific_guidance', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60)),
                ('event_date', models.DateField()),
                ('format_of_the_event', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн')], max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('organisations_holding_event', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('event_program', models.FileField(upload_to=tables.models.user_upload_path)),
                ('title_of_the_report', models.CharField(max_length=50)),
                ('copy_of_the_report', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_project', models.CharField(max_length=60)),
                ('number_of_the_project', models.IntegerField()),
                ('years_of_completion', models.CharField(max_length=100)),
                ('role_in_the_project', models.CharField(choices=[('director', 'Руководитель'), ('executor', 'Исполнитель')], max_length=10)),
                ('director_of_the_project', models.CharField(max_length=40)),
                ('copy_of_the_contract', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_monograph', models.CharField(max_length=60)),
                ('year_of_publication', models.IntegerField()),
                ('name_of_publication', models.CharField(max_length=100)),
                ('number_of_printed_sheets', models.IntegerField()),
                ('uploaded_monography', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_article', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('name_of_the_magazine', models.CharField(max_length=100)),
                ('year_of_publication', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to=tables.models.user_upload_path)),
                ('points', models.CharField(default='40', editable=False, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
